version: "3.9"
services:
  db:
    image: postgres:14.1
    volumes:
      - workshops_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
      POSTGRES_DB: "workshops_development"

  web:
    build:
      context: .
    command: [ "rails", "server", "-b", "0.0.0.0" ]
    environment:
      - DATABASE_URL=postgres://test:password@db:5432/workshops_development
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  workshops_db:
